# Generated by Django 5.1.5 on 2025-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultapp', '0002_alter_events_latitude_alter_events_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
